version: '2'
services:
    teamspeak:
        build: .
        command: /start
        ports:
          - "9987:9987/udp"
          - "30033:30033"
          - "10011:10011"
        volumes:
            - /srv/teamspeak:/data:Z
        restart: always
